name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run E2E tests
        uses: cypress-io/github-action@v1
        with:
          start: "npm run start"
          wait-on: "http://localhost:3000"
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          REACT_APP_FIRESTORE_API_BASE_URL: ${{ secrets.REACT_APP_FIRESTORE_API_BASE_URL }}
      # Deploy to gh-pages
      - name: Build
        if: github.ref == 'refs/heads/test-ghpages'
        run:
          npm run build-client
        env:
          REACT_APP_FIRESTORE_API_BASE_URL: ${{ secrets.REACT_APP_FIRESTORE_API_BASE_URL }}
      
      - name: Deploy
        if: github.ref == 'refs/heads/test-ghpages'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: packages/client/build
