name: End-to-end tests
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.8'
      - run: npm install
      - run: npm run bootstrap
      - name: Lint javscript code
        run: npm run lint
      - name: Archive eslint report
        uses: actions/upload-artifact@v1
        with:
          name: eslint-report
          path: .test/eslint-report.html
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build docker-compose stack
        run: docker-compose up -d --build
      - name: Check running containers
        run: docker ps -a
      - name: Check logs
        run: docker logs unitednepali-client
      # Run all Cypress tests
      - name: Run E2E tests
        uses: cypress-io/github-action@v1
        with:
          wait-on: "http://localhost"
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
